[window]
padding.x = 0
padding.y = 0
option_as_alt = "OnlyLeft" 

decorations = "none"
opacity = 1.0
blur = true

[font]
normal.family = "Iosevka"
normal.style = "Regular"
#normal.family = "Iosevka-Regular"
size = 25

[env]
TERM = "xterm-256color"

[terminal]

[terminal.shell]
program = "/bin/bash"
args = [ "--login" ]

[colors.primary]
background = "#000000"
foreground = "#e4e4ef"
